### ISSUE TITLE
How could we restore the private key from extended private key in bip32.py

### ISSUE THREAD

**Issue by keviny** [dginst/btclib#32]
There is a function address_from_xpub to generate the address from xpub.
Could we have a key_from_xprv to generate the private key from xprv in bip32.py as well?

**Comment by keviny** [comment]
You mean use bip32 to manipulate the extended private key and extended public key, and use wifaddress to convert the Point (pubKey) and Int (prvKey) to other formats, that makes a lot of sense to me. 

One other topic is using the generated private key to generate the second layer of the extended private/public key. 

seed=bip39.seed_from_mnemonic('xyz')

# Generate the first layer address
mprv=bip32.mprv_from_seed(seed, xkey_version.hex())
dmprv=bip32.derive(mprv, layer1_path)
dprv=bip32.prvkey_from_xpriv(dmprv)

# Generate the second layer address
mprv2=bip32.mprv_from_pri(dprv)  # or could we use bip32.mprv_from_seed here?
dmprv2=bip32.derive(mprv, layer2_path)

**Comment by fametrano** [comment]
with next release (later this month or early February, check the current master branch at fametrano/btclib) you will be able to use wif_from_xprv:
```
from btclib import bip32
from btclib.wif import p2pkh_address_from_wif
seed = b"00"*32  # better be random
rxprv = bip32.rootxprv_from_seed(seed)
path = "m/0h/0h/12"
xprv = bip32.derive(rxprv, path)
wif = bip32.wif_from_xprv(xprv)
address = p2pkh_address_from_wif(wif)
address2 = bip32.address_from_xpub(bip32.xpub_from_xprv(xprv))
```
with WIF being b'KyLk7s6Z1FtgYEVp3bPckPVnXvLUWNCcVL6wNt3gaT96EmzTKZwP' and both addresses being b'1Lbn3TbfPzM5AjQn84d4bugQN8W4bS1WAQ'
